### ISSUE TITLE
Code Reviewer

### ISSUE THREAD

**Issue by NightZan999** [TheImperialGod/TheImperialGod#12]
We need a code reviewer, basically someone who knows a lot about discord.py and about EJS and approving our website and more. I will be uploading the website soon and also updating the bot. 

That way we can use more Github automation and basically. If anyone wants to review the code, reply to this issue. 
Then I will see if your eligible and approve you or not. 

Thanks

**Comment by superzackx** [comment]
I know the website part and Python but not discord.py.

**Comment by NightZan999** [comment]
Sure. We can have you as our website reviewer. In github automation, @superzackx you will have to review the things we have worked over.
